-- UzHandy V7 starter schema for Supabase
create table if not exists public.estimate_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  service text not null,
  zip_code text,
  details text not null,
  preferred_contact text default 'Text',
  status text not null default 'new' check (status in ('new','contacted','scheduled','completed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.estimate_requests enable row level security;

-- Public website may create a request, but may not read customer requests.
create policy "public can submit estimate requests"
on public.estimate_requests for insert
to anon
with check (status = 'new');

-- Authenticated admin users can read/update requests.
create policy "authenticated admin can read requests"
on public.estimate_requests for select
to authenticated using (true);
create policy "authenticated admin can update requests"
on public.estimate_requests for update
to authenticated using (true) with check (true);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  service text not null,
  area text,
  description text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.projects enable row level security;
create policy "public can read published projects" on public.projects for select to anon using (published = true);
create policy "authenticated can manage projects" on public.projects for all to authenticated using (true) with check (true);
